### ISSUE TITLE
I want to create an ICP account through the API. Is there a way to do this?

### ISSUE THREAD

**Issue by hankeke** [dfinity/nns-js#113]
I want to create an ICP account through the API. Is there a way to do this? I want to write an app to create an account and transfer ICP tokens. At present, I haven’t found the corresponding API. Can I ask if this can be realized?

**Comment by peterpeterparker** [comment]
What do mean with "create an account"?

**Comment by hankeke** [comment]
An account is a wallet account。I want to create an ICP wallet account through the `nns-js`  sdk;
eg: 
I can't find an ICP account that can be created with this SDK in the code

![image](https://user-images.githubusercontent.com/11770232/173288828-5f7dc73b-5636-47ae-bf6f-e22470ded0a6.png)

**Comment by peterpeterparker** [comment]
> The logic is the same as that for creating accounts.

Thanks for the details. We do not expose at the moment such features as "create nns-dapp linked account or hardware wallet" in `nns-js`. I think the main reason is that to do so we also need the nns-dapp backend canister that is also not exposed in nns-js.

I'll close the question since it is cannot be resolved but let me know if you have further question.
